import {
  BadRequestException,
  Body,
  Controller,
  Get,
  Header,
  Post,
} from "@nestjs/common"
import { AgentAuthStateService } from "./agent-auth-state.service"
import { Public } from "./public.decorator"

@Controller()
export class SetupController {
  constructor(private readonly authState: AgentAuthStateService) {}

  @Public()
  @Get("setup")
  @Header("Content-Type", "text/html; charset=utf-8")
  async setupPage() {
    await this.authState.assertSetupAvailable()
    const status = await this.authState.getRotationState()

    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>DockSentinel Agent Setup</title>
    <style>
      :root {
        color-scheme: light;
        font-family: "Geist", ui-sans-serif, system-ui, sans-serif;
      }
      body {
        margin: 0;
        min-height: 100vh;
        background: linear-gradient(135deg, #f6f8fb 0%, #edf2f7 100%);
        color: #132238;
      }
      main {
        max-width: 640px;
        margin: 0 auto;
        padding: 40px 20px 56px;
      }
      .panel {
        border: 1px solid rgba(19, 34, 56, 0.12);
        border-radius: 28px;
        background: rgba(255, 255, 255, 0.94);
        box-shadow: 0 24px 80px -40px rgba(10, 22, 40, 0.4);
        padding: 28px;
      }
      .eyebrow {
        display: inline-flex;
        padding: 6px 10px;
        border-radius: 999px;
        background: rgba(36, 96, 164, 0.1);
        color: #2460a4;
        font-size: 12px;
        font-weight: 700;
        letter-spacing: 0.08em;
        text-transform: uppercase;
      }
      h1 {
        margin: 14px 0 10px;
        font-size: 34px;
        line-height: 1.08;
      }
      p {
        margin: 0;
        line-height: 1.6;
        color: #4f6177;
      }
      .status {
        margin-top: 22px;
        display: inline-flex;
        align-items: center;
        gap: 10px;
        padding: 10px 14px;
        border-radius: 999px;
        background: #eef5ff;
        color: #1f4f87;
        font-weight: 600;
      }
      form {
        margin-top: 28px;
        display: grid;
        gap: 14px;
      }
      label {
        font-size: 14px;
        font-weight: 600;
      }
      input {
        width: 100%;
        box-sizing: border-box;
        border: 1px solid rgba(19, 34, 56, 0.18);
        border-radius: 18px;
        padding: 14px 16px;
        font-size: 15px;
        outline: none;
      }
      input:focus {
        border-color: #2460a4;
        box-shadow: 0 0 0 4px rgba(36, 96, 164, 0.14);
      }
      button {
        border: 0;
        border-radius: 18px;
        padding: 14px 18px;
        background: linear-gradient(135deg, #1f4f87 0%, #2460a4 100%);
        color: white;
        font-size: 15px;
        font-weight: 700;
        cursor: pointer;
      }
      button:disabled {
        opacity: 0.6;
        cursor: wait;
      }
      .hint {
        margin-top: 20px;
        font-size: 14px;
        color: #64748b;
      }
      .result {
        margin-top: 16px;
        min-height: 22px;
        font-size: 14px;
        font-weight: 600;
      }
      .result.error {
        color: #b42318;
      }
      .result.success {
        color: #157347;
      }
    </style>
  </head>
  <body>
    <main>
      <section class="panel">
        <div class="eyebrow">DockSentinel Agent</div>
        <h1>Local token setup</h1>
        <p>
          Paste the temporary bootstrap token generated by the main DockSentinel app.
          This page is available only while the agent is waiting for setup or rotation.
        </p>
        <div class="status">Current state: <span id="state">${status}</span></div>

        <form id="token-form">
          <div>
            <label for="token">Bootstrap token</label>
            <input id="token" name="token" type="password" autocomplete="off" placeholder="dsa_..." required />
          </div>
          <button id="submit" type="submit">Save token</button>
        </form>

        <div id="result" class="result"></div>
        <div class="hint">
          After saving the token, return to the main DockSentinel app and wait for the
          automatic completion or click <strong>Complete rotation</strong>.
        </div>
      </section>
    </main>
    <script>
      const form = document.getElementById("token-form");
      const state = document.getElementById("state");
      const result = document.getElementById("result");
      const submit = document.getElementById("submit");

      form.addEventListener("submit", async (event) => {
        event.preventDefault();
        result.textContent = "";
        result.className = "result";
        submit.disabled = true;
        const token = document.getElementById("token").value.trim();

        try {
          const response = await fetch("/agent/v1/admin/rotation/token", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ token }),
          });
          const data = await response.json().catch(() => ({}));
          if (!response.ok) {
            throw new Error(data.message || "Could not save token");
          }
          state.textContent = data.state || "ready_to_complete";
          result.textContent = "Token saved. You can go back to DockSentinel and complete the rotation.";
          result.classList.add("success");
          document.getElementById("token").value = "";
        } catch (error) {
          result.textContent = error instanceof Error ? error.message : String(error);
          result.classList.add("error");
        } finally {
          submit.disabled = false;
        }
      });
    </script>
  </body>
</html>`
  }

  @Public()
  @Post("agent/v1/admin/rotation/token")
  async saveRotationToken(@Body("token") token?: string) {
    const value = token?.trim()
    if (!value) {
      throw new BadRequestException("token is required")
    }

    const state = await this.authState.saveBootstrapToken(value)
    return {
      ok: true as const,
      state,
    }
  }
}
